# CSV - Python Standard Library

In [6]:
import csv
import numpy as np

In [18]:
data = []

# with open("data.csv") as csv_file:
    
#     csv_reader = csv.DictReader(csv_file)
    
#     for row in csv_reader:
#         # data.append(list(row.values()))
#         data.append([ int(v) for v in row.values() ])

with open("data.csv") as csv_file:
    
    csv_reader = csv.reader(csv_file)
    
    next(csv_reader)
    
    for row in csv_reader:
#         data.append(row)
        data.append([ int(v) for v in row ])


data

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [13]:
# nums = np.array(data, dtype=int)
nums = np.array(data)

In [14]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
nums.dtype

dtype('int32')

# CSV - NumPy

In [19]:
data = np.loadtxt('data.csv', delimiter=',', skiprows=1, dtype=int)

data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
display(np.max(data))
display(np.min(data))

15

1

In [24]:
display(np.max(data, axis=0))
display(np.min(data, axis=0))

array([11, 12, 13, 14, 15])

array([1, 2, 3, 4, 5])

In [25]:
display(np.max(data, axis=1))
display(np.min(data, axis=1))

array([ 5, 10, 15])

array([ 1,  6, 11])

In [28]:
display(data.max())
display(data.max(axis=0))

15

array([11, 12, 13, 14, 15])

In [37]:
display(np.sum(data))
display(np.sum(data, axis=0))
display(np.sum(data, axis=1))

display(data.sum())
display(data.sum(axis=0))
display(data.sum(axis=1))

120

array([18, 21, 24, 27, 30])

array([15, 40, 65])

120

array([18, 21, 24, 27, 30])

array([15, 40, 65])

In [34]:
display(sum(data)) # built-in Python sum is display(np.sum(data, axis=0))

array([18, 21, 24, 27, 30])